"""Generate the offline preview's palette data from the shared color roles."""

import argparse
import json
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument(
        "repo", nargs="?", type=Path, default=Path(__file__).resolve().parent.parent
    )
    args = parser.parse_args()
    palette = json.loads((args.repo / "lib/palette.json").read_text())
    output = (
        "// Generated by scripts/palette-preview.py from lib/palette.json.\n"
        + "const workstationPalette = "
        + json.dumps(palette, indent=2)
        + ";\n"
        + "for (const [role, color] of Object.entries(workstationPalette)) {\n"
        + "  document.documentElement.style.setProperty(`--palette-${role}`, color);\n"
        + "}\n"
        + 'for (const element of document.querySelectorAll("[data-palette]")) {\n'
        + "  element.textContent = workstationPalette[element.dataset.palette];\n"
        + "}\n"
    )
    destination = args.repo / "docs/palette.js"
    if args.check:
        if not destination.is_file() or destination.read_text() != output:
            parser.error("Preview palette is stale; run just palette-update")
    else:
        destination.write_text(output)


if __name__ == "__main__":
    main()
